export { default as Home } from './Home';
export { default as Register } from './Register';
export { default as AccountCreated } from './AccountCreated';
export { default as Login } from './Login';
export { default as ForgotPassword } from './ForgotPassword';
export { default as Movies } from './Movies';
export { default as Movie } from './Movie';
export { default as TVShows } from './TVShows';
export { default as TVShow } from './TVShow';